[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/companies"
  to = "/.netlify/functions/companies"
  status = 200

[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from = "/api/new-jobs"
  to = "/.netlify/functions/new-jobs"
  status = 200

[[redirects]]
  from = "/api/redis-debug"
  to = "/.netlify/functions/redis-debug"
  status = 200

[[redirects]]
  from = "/api/jobs/search"
  to = "/.netlify/functions/jobs-search"
  status = 200
